FROM node:lts as BUILDER

ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG DATABASE_SYNCHRONIZE
ARG DATABASE_AUTOLOADENTITIES
ARG AUTH_SECRET
ARG REDIS_SECONDS
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASS
ARG EXPIRES_IN
ARG PAGINATION_PAGE
ARG PAGINATION_LIMIT

ENV DATABASE_HOST="${DATABASE_HOST}"
ENV DATABASE_PORT="${DATABASE_PORT}"
ENV DATABASE_USERNAME="${DATABASE_USERNAME}"
ENV DATABASE_PASSWORD="${DATABASE_PASSWORD}"
ENV DATABASE_SYNCHRONIZE="${DATABASE_SYNCHRONIZE}"
ENV DATABASE_AUTOLOADENTITIES="${DATABASE_AUTOLOADENTITIES}"
ENV AUTH_SECRET="${AUTH_SECRET}"
ENV REDIS_SECONDS="${REDIS_SECONDS}"
ENV REDIS_HOST="${REDIS_HOST}"
ENV REDIS_PORT="${REDIS_PORT}"
ENV REDIS_PASS="${REDIS_PASS}"
ENV EXPIRES_IN="${EXPIRES_IN}"
ENV PAGINATION_PAGE="${PAGINATION_PAGE}"
ENV PAGINATION_LIMIT="${PAGINATION_LIMIT}"

WORKDIR /builder/
ADD . .

RUN npm i && npm build

FROM node:alpine as prod

WORKDIR /APP

# bug: the nestjs app src/app.module.ts#I18nModule.forRoot watch src dir
COPY --from=BUILDER /builder/dist /APP/dist
COPY --from=BUILDER ["/builder/locales.json", "/builder/package.json", "/APP/"]

RUN npm i --production

EXPOSE 3000
VOLUME [ "./dist/data" ]
CMD ["node", "./dist/main.js"]
